### PR TITLE
DVOP-3032 Read only access to root file system.

### PR DESCRIPTION
**Pull request by harishkm2k**

### CODE REVIEW

**Review by tobafolaranmi-ch — APPROVED** [review]
LGTM

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Review by Elliseggs11 — APPROVED** [review]

**Comment by ch-code-analysis** [comment]
CI: No IaC security warnings found

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Pull request merged**
